import multiprocessing
import pyspark
import json
from batch_consumer import Batch_Processing
from pyspark import SparkContext
from pyspark.sql import SparkSession
import pyspark.sql.functions as f
import boto3
import os
from airflow.models import DAG
from datetime import datetime
from datetime import timedelta
from airflow.operators.bash import BashOperator
from airflow.operators.python import PythonOperator
from airflow.models import Variable
from pyspark.sql.functions import col


default_args = {
    'owner': 'balany1',
    'depends_on_past': False,
    'email': ['andrewmcnamara@live.co.uk'],
    'email_on_failure': False,
    'email_on_retry': False,
    'retries': 1,
    'start_date': datetime(2023, 2, 8), # If you set a datetime previous to the curernt date, it will try to backfill
    'retry_delay': timedelta(minutes=5),
    'end_date': datetime(2024, 1, 1),
}

def create_raw_data_folder(self):
        '''Creates folder for data to be stored
        '''
        if os.path.exists("./raw_data") == False:
            raw_data = os.mkdir("./raw_data")
        print('raw_data directory created')

def find_max_followers(df):
      '''
      Args:
      df = the spark dataframe produced from the SparkSession
       '''
      
      df.sort(col('follower_count').desc()).show()
     

def find_most_common_categories(df):
      '''Finds most common categories generated byt the user emulation
      
      Args:
      df = the spark dataframe produced from the SparkSession
      '''

      df.groupBy('category').count().sort(col('count').desc()).show()

Batch = Batch_Processing()

with DAG(dag_id='dag_spark',
         default_args=default_args,
         schedule_interval='09 13 * * *',
         catchup=False,
         tags=['spark']
         ) as dag:
    # define task
    Spark_task = PythonOperator(
        task_id = 'run_spark_job',
        python_callable = Batch.spark,
        )
        
        
        
